module.exports = {
  addfishinfo: require("./admin/addfishinfo"),
  deletefishinfo: require("./admin/deletefishinfo"),
  editfishinfo: require("./admin/editfishinfo"),
  addcon: require("./container/addcon"),
  addfish: require("./container/addfish"),
  coninfo: require("./container/coninfo"),
  deletecon: require("./container/deletecon"),
  editcon: require("./container/editcon"),
  feed: require("./container/feed"),
  level: require("./container/level"),
  water: require("./container/water"),
  fishinfo: require("./fish/fishinfo"),
  addcomment: require("./tip/addcomment"),
  addtip: require("./tip/addtip"),
  alltips: require("./tip/alltips"),
  deletecommnet: require("./tip/deletecomment"),
  deletetip: require("./tip/deletetip"),
  edittip: require("./tip/edittip"),
  editpwd: require("./user/editpwd"),
  login: require("./user/login"),
  logout: require("./user/logout"),
  signout: require("./user/signout"),
  signup: require("./user/signup"),
  userinfo: require("./user/userinfo"),
};
